# Generated by Django 5.2.5 on 2025-10-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pool',
            field=models.ManyToManyField(to='backend.teacherpool'),
        ),
    ]
