# Generated by Django 5.2.5 on 2025-10-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_teacher_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teached_subjects',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
