# Generated by Django 5.2.5 on 2025-10-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_teacher_teached_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teached_subjects',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teached_subjects',
            field=models.ManyToManyField(to='backend.subject'),
        ),
    ]
