# Generated by Django 5.2.5 on 2025-10-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_teacher_teached_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='border',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='pairable',
            field=models.ManyToManyField(to='backend.subject'),
        ),
    ]
