# Generated by Django 5.2.5 on 2025-10-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_subject_border_subject_pairable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='pairable',
            field=models.ManyToManyField(blank=True, null=True, to='backend.subject'),
        ),
    ]
