# Generated by Django 5.2.5 on 2025-10-31 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_subject_pairable'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student_group',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='backend.studentgroup'),
            preserve_default=False,
        ),
    ]
