# Generated by Django 5.2.5 on 2025-11-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_lesson_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ManyToManyField(to='backend.studentgroup')),
                ('req_set', models.ManyToManyField(to='backend.requirementset')),
                ('subjects', models.ManyToManyField(to='backend.subject')),
            ],
        ),
    ]
