# Generated by Django 5.2.5 on 2025-11-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_subjectblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectblock',
            old_name='group',
            new_name='groups',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='pairable',
        ),
    ]
