# Generated by Django 5.2.5 on 2025-11-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_group_subjectblock_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectblock',
            name='numbers',
            field=models.JSONField(default={}),
        ),
    ]
