# Generated by Django 5.2.5 on 2025-11-05 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_subjectblock_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectblock',
            name='req_set',
        ),
        migrations.AddField(
            model_name='subjectblock',
            name='req_set',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.requirementset'),
            preserve_default=False,
        ),
    ]
