# Generated by Django 5.2.5 on 2025-11-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_subjectblock_req_set_subjectblock_req_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectblock',
            name='max_number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subjectblock',
            name='power_block',
            field=models.BooleanField(default=False),
        ),
    ]
