# Generated by Django 5.2.5 on 2025-11-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_subjectblock_max_number_subjectblock_power_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='preferences',
        ),
        migrations.AddField(
            model_name='room',
            name='compatible_subjects',
            field=models.ManyToManyField(to='backend.subject'),
        ),
    ]
